name: gihub workflow with feature

on:
  push:

jobs:
  build: 
     name: create a PR
     runs-on: ubuntu-latest
     if: github.event_name == 'push'
     steps:
     - name: checkout code
       uses: actions/checkout@v3
       
     - name: install dependancy
       uses: actions/upload-artifacts@v4
     - name: download
       uses: actions/download-artifacts@v4
 
     - name: Cache Primes
       id: cache-primes
       uses: actions/cache@v4
       with:
         path: prime-numbers
         key: ${{ runner.os }}-prime
      
     - name: Generate Prime Numbers
       if: steps.cache-primes.outputs.cache-hit != 'true'
       run: /generate-primes.sh -d prime-numbers
       
  
